name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.0'
        cache: true

    - name: Install dependencies
      run: |
        go mod download
        # Install ffmpeg for audio tests
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Run tests
      env:
        SOUNDCLOUD_CLIENT_ID: "test_client_id_for_ci"
      run: go test -v ./...

    - name: Run tests with coverage
      env:
        SOUNDCLOUD_CLIENT_ID: "test_client_id_for_ci"
      run: go test -v -coverprofile=coverage.out ./...

    - name: Generate coverage report
      run: go tool cover -html=coverage.out -o coverage.html

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.html 