name: openapi-generation

on:
  push:
    paths:
      - 'cmd/**'
      - 'internal/server/**'
      - 'internal/job/**'
      - 'internal/domain/**'
  pull_request:
    paths:
      - 'cmd/**'
      - 'internal/server/**'
      - 'internal/job/**'
      - 'internal/domain/**'

jobs:
  generate-openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install swag CLI
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate OpenAPI spec
        run: swag init -g cmd/main.go -o openapi

      - name: Upload OpenAPI artifact
        uses: actions/upload-artifact@v3
        with:
          name: openapi-spec
          path: openapi/swagger.json

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install openapi-python-client
        run: python -m pip install --quiet --upgrade openapi-python-client

      - name: Generate Python client
        run: openapi-python-client generate --path openapi/swagger.json --output python_client --force

      - name: Upload Python client artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-client
          path: python_client