name: Publish Python Client

on:
  push:
    branches:
      - main
    paths:
      - 'clients/python/**'
  workflow_dispatch:
      
permissions:
  contents: write
  packages: write
  actions: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep -o 'version = "[^"]*"' clients/python/pyproject.toml | cut -d'"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and publish package
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: make python-publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          tag_name: python-client-v${{ steps.get_version.outputs.version }}
          name: Python Client Release v${{ steps.get_version.outputs.version }}
          body: |
            Automated release of Python client package.
            
            Generated from commit: ${{ github.sha }}
          files: |
            clients/python/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 